services:
  - name: local-route-finder-backend
    type: web
    env: node
    root: ./
    buildCommand: cd backend && npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm start
    cache:
      - node_modules
      - ~/.npm
      - backend/dist
